// Replicate Rendering API (Private Deployment)
// Pipeline: Upload Image -> Run Private Deployment (visionrender) -> Return Result

const Replicate = require('replicate');

module.exports = async (req, res) => {
    // Enable CORS
    const allowedOrigins = [
        'https://v2rbuilds.com',
        'https://www.v2rbuilds.com',
        'http://localhost:5500',
        'http://127.0.0.1:5500',
        'https://v2-r-builds.vercel.app',
        'http://localhost:8080'
    ];
    const origin = req.headers.origin;
    if (allowedOrigins.includes(origin)) res.setHeader('Access-Control-Allow-Origin', origin);
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') return res.status(200).end();
    if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

    try {
        const { imageUrl, userPrompt } = req.body;
        if (!imageUrl) return res.status(400).json({ error: 'Missing image URL' });

        const REPLICATE_API_TOKEN = process.env.REPLICATE_API_TOKEN;
        if (!REPLICATE_API_TOKEN) return res.status(500).json({ error: 'Server config error: Missing Replicate API Token' });

        const replicate = new Replicate({
            auth: REPLICATE_API_TOKEN,
        });

        console.log('Starting Replicate Render Pipeline (Deployment)...');
        console.log('User Prompt:', userPrompt);
        console.log('Image URL:', imageUrl);

        // Usage: saiful-mahmood/visionrender
        let prediction = await replicate.deployments.predictions.create(
            "saiful-mahmood",
            "visionrender",
            {
                input: {
                    image: imageUrl,
                    prompt: `modern interior design, high quality, photorealistic, ${userPrompt}`,
                    negative_prompt: "low quality, text, logos, watermark, ugly, blurry, artifacts, low resolution, cartoon, painting, illustration, messy, clutter",
                    num_samples: 1,
                    image_resolution: "512", // Adjust if your model supports higher resolution
                    ddim_steps: 20,
                    scale: 9,
                    eta: 0,
                    a_prompt: "best quality, extremely detailed",
                    n_prompt: "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality"
                }
            }
        );

        console.log('Prediction Created. ID:', prediction.id);

        // Wait for the result
        prediction = await replicate.wait(prediction);

        console.log('Replicate Output:', prediction.output);

        if (!prediction.output || prediction.output.length === 0) {
            throw new Error('Replicate generated no output.');
        }

        // Replicate output is typically an array of URLs for image generation models
        const finalImage = Array.isArray(prediction.output) ? prediction.output[prediction.output.length - 1] : prediction.output;

        return res.status(200).json({
            success: true,
            renderUrl: finalImage,
            description: "Modernized visualization generated by Replicate (visionrender).",
            modelUsed: 'saiful-mahmood/visionrender'
        });

    } catch (error) {
        console.error('Render error:', error);
        return res.status(500).json({
            success: false,
            error: error.message,
            fallbackReason: 'Replicate Service Error'
        });
    }
};
