// Replicate Rendering API (Private Deployment)
// Pipeline: Start Prediction (POST) -> Poll for Status (GET) -> Return Result

const Replicate = require('replicate');

module.exports = async (req, res) => {
    // Enable CORS
    const allowedOrigins = [
        'https://v2rbuilds.com',
        'https://www.v2rbuilds.com',
        'http://localhost:5500',
        'http://127.0.0.1:5500',
        'https://v2-r-builds.vercel.app',
        'http://localhost:8080'
    ];
    const origin = req.headers.origin;
    if (allowedOrigins.includes(origin)) res.setHeader('Access-Control-Allow-Origin', origin);
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') return res.status(200).end();

    const REPLICATE_API_TOKEN = process.env.REPLICATE_API_TOKEN;
    if (!REPLICATE_API_TOKEN) return res.status(500).json({ error: 'Server config error: Missing Replicate API Token' });

    const replicate = new Replicate({
        auth: REPLICATE_API_TOKEN,
    });

    try {
        // --- GET: CHECK STATUS ---
        if (req.method === 'GET') {
            const { id } = req.query;
            if (!id) return res.status(400).json({ error: 'Missing prediction ID' });

            const prediction = await replicate.predictions.get(id);

            if (prediction.status === 'succeeded') {
                // Replicate output is typically an array of URLs for image generation models
                // It might be a single string or an array depending on the model
                let finalImage = prediction.output;
                if (Array.isArray(prediction.output)) {
                    finalImage = prediction.output[prediction.output.length - 1];
                }

                return res.status(200).json({
                    status: 'succeeded',
                    renderUrl: finalImage,
                    description: "Modernized visualization generated by Replicate (visionrender).",
                });
            } else if (prediction.status === 'failed' || prediction.status === 'canceled') {
                return res.status(200).json({ status: 'failed', error: prediction.error });
            } else {
                // still processing or starting
                return res.status(200).json({ status: prediction.status });
            }
        }

        // --- POST: START PREDICTION ---
        if (req.method === 'POST') {
            const { imageUrl, userPrompt } = req.body;
            if (!imageUrl) return res.status(400).json({ error: 'Missing image URL' });

            console.log('Starting Replicate Prediction (Deployment)...');
            console.log('User Prompt:', userPrompt);

            // Usage: saiful-mahmood/visionrender
            const prediction = await replicate.deployments.predictions.create(
                "saiful-mahmood",
                "visionrender",
                {
                    input: {
                        image: imageUrl,
                        prompt: `modern interior design, high quality, photorealistic, ${userPrompt}`,
                        negative_prompt: "low quality, text, logos, watermark, ugly, blurry, artifacts, low resolution, cartoon, painting, illustration, messy, clutter",
                        num_samples: 1,
                        image_resolution: "512",
                        ddim_steps: 20,
                        scale: 9,
                        eta: 0,
                        a_prompt: "best quality, extremely detailed",
                        n_prompt: "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality"
                    }
                }
            );

            console.log('Prediction Started. ID:', prediction.id);

            // Return success immediately with the ID to poll
            return res.status(200).json({
                success: true,
                predictionId: prediction.id,
                status: "starting"
            });
        }

        return res.status(405).json({ error: 'Method not allowed' });

    } catch (error) {
        console.error('API Error:', error);
        return res.status(500).json({
            success: false,
            error: error.message,
            fallbackReason: 'Replicate Service Error'
        });
    }
};
